name: Scrape Financial Data
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies and run scraper
        run: |
          pip install -r requirements.txt
          playwright install chromium
          python backend/scraper.py
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}